site_name: TomatoET
site_url: https://tomatoet.github.io/
theme:
  name: material

  icon: 
    logo: material/github
  
  language: zh

  features:
    - navigation.top # 返回顶部按钮
    - navigation.tabs # 顶部分类标签
    - search.highlight # 搜索结果高亮显示
    
  palette:
    primary: black




copyright: Copyright © 2025 TomatoET All Rights Reserved

nav:
  - 首页:
    - HelloWorld: index.md  
    - 更新动态: ChangeLog.md
  - 开源空间:
    - 开源目录: Open/Open.md
  - 知识分享:
    - Linux: 
      - 第一章: Blog/Linux/Linux.md  
    - RadioFrequency: 
      - 射频电路设计: Blog/RadioFrequency/RF_Circuit_Design.md
    - Android: 
      - 第一章: Blog/Android/Android.md
  - 关于我们:
    - AboutUs: AboutUs.md
  

  