site_url: https://tomatoet.github.io/TomatoET.github.io/  # 替换为你的实际URL
use_directory_urls: true  # 启用目录URL模式（推荐）

site_name: TomatoET
theme: 
  name: material

  icon: 
    logo: material/github
  plugins:
  - search:
      lang:
        - en
        - ru

  language: zh
  palette:
    primary: black


  features:
    - navigation.instant
    - navigation.top # 返回顶部按钮
    - navigation.tabs # 顶部分类标签
    - search.highlight # 搜索高亮显示

copyright: Copyright @ 2025 TomatoET ALL Rights Reserved





nav:
- 首页:
  - 介绍: 首页文章\介绍.md
  - 关于我们: 联系方式.md